// Code generated by mockery v2.42.0. DO NOT EDIT.

package repository

import (
	auditlog "github.com/audit-log-service/internal/repository/auditlog"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

// GetAuditLog provides a mock function with given fields:
func (_m *MockRegistry) GetAuditLog() auditlog.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLog")
	}

	var r0 auditlog.Repository
	if rf, ok := ret.Get(0).(func() auditlog.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auditlog.Repository)
		}
	}

	return r0
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
