// Code generated by mockery v2.42.0. DO NOT EDIT.

package auditlog

import (
	context "context"

	model "github.com/audit-log-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// GetAuditLogs provides a mock function with given fields: ctx, criteria
func (_m *MockController) GetAuditLogs(ctx context.Context, criteria model.FilterCriteria) ([]model.AuditLog, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLogs")
	}

	var r0 []model.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.FilterCriteria) ([]model.AuditLog, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.FilterCriteria) []model.AuditLog); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.FilterCriteria) error); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleAuditLogMessage provides a mock function with given fields: ctx, log
func (_m *MockController) HandleAuditLogMessage(ctx context.Context, log model.AuditLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for HandleAuditLogMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuditLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
