name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Docker Compose Up
        run: docker compose up -d --build

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker compose -y

      - name: Run Tests
        run: make test

      - name: Build Application
        run: make build

      - name: Docker Compose Down
        if: always()
        run: docker compose down -v --remove-orphans

  fake_deploy:
    name: Fake Deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Fake deploy
        run: |
          echo "Starting fake deploy..."
          sleep 5
          echo "Fake deploy completed."
